global using APC.Application.Common.Interfaces;
global using Microsoft.EntityFrameworkCore;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using MediatR;
global using System.Security.Cryptography;